import { Metadata } from 'next'
import Link from 'next/link'
import { Shield, FileCheck, Scale, ArrowRight, CheckCircle2, AlertTriangle, Building2, BookOpen, ExternalLink } from 'lucide-react'

export const metadata: Metadata = {
  title: 'ASIC AI Governance Compliance for Australia | Kuneo',
  description: 'Complete guide to Australian AI agent compliance. Meet ASIC RG 97, ERS standards, SMSF requirements, and AML/CTF obligations for autonomous financial agents in Australia.',
  keywords: ['ASIC compliance', 'Australian AI regulation', 'RG 97 compliance', 'SMSF AI agents', 'AML CTF Australia', 'financial AI Australia'],
  openGraph: {
    title: 'Australian AI Compliance (ASIC) | Kuneo',
    description: 'Deploy compliant AI agents in Australia. Full ASIC, ERS, and SMSF compliance framework.',
    url: 'https://kuneo.tech/ai-governance/regulations/australia',
    siteName: 'Kuneo',
    locale: 'en_AU',
    type: 'article',
  },
}

export default function AustraliaRegulationsPage() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    "headline": "ASIC AI Governance Compliance Framework for Australia",
    "description": "Comprehensive guide to deploying compliant AI agents under Australian regulation",
    "author": {
      "@type": "Organization",
      "name": "Kuneo"
    },
    "publisher": {
      "@type": "Organization",
      "name": "Kuneo",
      "logo": {
        "@type": "ImageObject",
        "url": "https://kuneo.tech/logo.png"
      }
    },
    "datePublished": "2026-01-28",
    "dateModified": "2026-01-28"
  }

  const regulations = [
    {
      code: 'RG 97',
      title: 'Financial Product Advice Disclosure',
      description: 'Requirements for disclosure of AI-generated financial advice and algorithmic trading decisions',
      requirements: [
        'Disclose when advice is generated by AI systems',
        'Maintain records of AI model decision-making processes',
        'Provide clear explanations of automated recommendations',
        'Ensure human oversight of AI-generated advice'
      ],
      kuneoSolution: 'Immutable audit trails log every AI decision with human oversight flags and explainability metadata'
    },
    {
      code: 'ERS',
      title: 'Electronic Record-Keeping Standards',
      description: 'Standards for maintaining electronic records of financial transactions and advice',
      requirements: [
        'Records must be easily retrievable and reproducible',
        'Maintain records for 7 years minimum',
        'Ensure record authenticity and integrity',
        'Support regulatory inspection and audit'
      ],
      kuneoSolution: 'Append-only cryptographic logs with timestamp proof and one-click PDF/JSON export for ASIC inspections'
    },
    {
      code: 'SMSF',
      title: 'Self-Managed Super Fund Compliance',
      description: 'Requirements for AI agents managing SMSF investments',
      requirements: [
        'Sole purpose test: investments must be for retirement benefits',
        'In-house asset rules (< 5% of fund value)',
        'Arms length transaction requirements',
        'Annual audit and compliance reporting'
      ],
      kuneoSolution: 'Pre-configured SMSF guardrails with automatic rule enforcement and annual compliance report generation'
    },
    {
      code: 'AML/CTF',
      title: 'Anti-Money Laundering & Counter-Terrorism Financing',
      description: 'Transaction monitoring and suspicious activity reporting requirements',
      requirements: [
        'Real-time transaction monitoring',
        'Suspicious matter reporting (SMR) to AUSTRAC',
        'Customer identification and verification',
        'Record keeping for 7 years'
      ],
      kuneoSolution: 'Real-time pattern detection with automatic flagging and AUSTRAC-compatible reporting formats'
    }
  ]

  const implementationSteps = [
    {
      step: 1,
      title: 'Initial Compliance Assessment',
      description: 'Evaluate your AI agent against ASIC requirements',
      action: 'Use Kuneo compliance scanner'
    },
    {
      step: 2,
      title: 'Configure ASIC Rule Templates',
      description: 'Deploy pre-built rules for RG 97, ERS, SMSF, and AML/CTF',
      action: 'One-click template installation'
    },
    {
      step: 3,
      title: 'Enable Audit Trail Logging',
      description: 'Activate cryptographic logging for all agent decisions',
      action: 'Automatic append-only logs'
    },
    {
      step: 4,
      title: 'Set Up Human Oversight',
      description: 'Configure approval workflows for high-value transactions',
      action: 'Define thresholds and alerts'
    },
    {
      step: 5,
      title: 'Generate Compliance Reports',
      description: 'Export audit logs in ASIC-approved formats',
      action: 'One-click PDF/JSON export'
    }
  ]

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      <div className="space-y-16">
        {/* Hero */}
        <section>
          <div className="mb-6 flex items-center gap-2 text-sm text-gray-600">
            <Link href="/ai-governance" className="hover:text-blue-600">AI Governance</Link>
            <span>/</span>
            <Link href="/ai-governance/regulations" className="hover:text-blue-600">Regulations</Link>
            <span>/</span>
            <span className="font-semibold text-gray-900">Australia</span>
          </div>

          <div className="mb-8 flex items-center gap-4">
            <span className="text-6xl">🇦🇺</span>
            <div>
              <h1 className="mb-2 text-4xl font-bold text-gray-900">
                Australian AI Agent Compliance
              </h1>
              <p className="text-xl text-gray-600">
                ASIC, ERS, SMSF & AML/CTF Requirements for Autonomous Financial Agents
              </p>
            </div>
          </div>

          <div className="rounded-2xl border border-blue-200 bg-gradient-to-br from-blue-50 to-indigo-50 p-8">
            <h2 className="mb-4 text-2xl font-bold text-gray-900">
              What is ASIC AI Governance Compliance?
            </h2>
            <p className="mb-6 text-lg leading-relaxed text-gray-700">
              ASIC AI Governance Compliance ensures that autonomous financial agents operating in Australia 
              meet the Australian Securities and Investments Commission's standards for disclosure, record-keeping, 
              and consumer protection. Kuneo provides the infrastructure to deploy AI agents that automatically 
              comply with RG 97, ERS, SMSF, and AML/CTF requirements.
            </p>
            <div className="grid gap-4 md:grid-cols-2">
              <div className="flex items-start gap-3 rounded-lg border border-emerald-200 bg-white p-4">
                <CheckCircle2 className="mt-1 h-5 w-5 flex-shrink-0 text-emerald-600" />
                <div>
                  <p className="font-semibold text-gray-900">For Financial Advisers</p>
                  <p className="text-sm text-gray-600">RG 97 compliant AI advice disclosure</p>
                </div>
              </div>
              <div className="flex items-start gap-3 rounded-lg border border-emerald-200 bg-white p-4">
                <CheckCircle2 className="mt-1 h-5 w-5 flex-shrink-0 text-emerald-600" />
                <div>
                  <p className="font-semibold text-gray-900">For SMSF Trustees</p>
                  <p className="text-sm text-gray-600">Automated compliance with sole purpose test</p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Regulatory Framework */}
        <section>
          <h2 className="mb-8 text-3xl font-bold text-gray-900">
            Australian Regulatory Framework for AI Agents
          </h2>
          <div className="space-y-6">
            {regulations.map((reg) => (
              <div key={reg.code} className="rounded-2xl border border-gray-200 bg-white p-8 shadow-lg">
                <div className="mb-6 flex items-start justify-between">
                  <div>
                    <div className="mb-2 inline-flex items-center gap-2 rounded-full bg-emerald-100 px-3 py-1 text-sm font-semibold text-emerald-700">
                      {reg.code}
                    </div>
                    <h3 className="mb-2 text-2xl font-bold text-gray-900">{reg.title}</h3>
                    <p className="text-gray-600">{reg.description}</p>
                  </div>
                  <Scale className="h-12 w-12 text-gray-300" />
                </div>

                <div className="grid gap-8 md:grid-cols-2">
                  <div>
                    <h4 className="mb-3 font-semibold text-gray-900">Requirements</h4>
                    <ul className="space-y-2">
                      {reg.requirements.map((req, idx) => (
                        <li key={idx} className="flex items-start gap-2 text-sm text-gray-700">
                          <AlertTriangle className="mt-0.5 h-4 w-4 flex-shrink-0 text-orange-500" />
                          <span>{req}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                  <div>
                    <h4 className="mb-3 font-semibold text-gray-900">Kuneo Solution</h4>
                    <div className="rounded-lg bg-emerald-50 p-4">
                      <p className="text-sm text-gray-700">{reg.kuneoSolution}</p>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Implementation Guide */}
        <section className="rounded-2xl bg-gray-50 p-8">
          <h2 className="mb-8 text-3xl font-bold text-gray-900">
            5-Step ASIC Compliance Implementation
          </h2>
          <div className="space-y-4">
            {implementationSteps.map((item) => (
              <div key={item.step} className="flex gap-6 rounded-xl border border-gray-200 bg-white p-6">
                <div className="flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-emerald-600 to-emerald-700 text-lg font-bold text-white">
                  {item.step}
                </div>
                <div className="flex-1">
                  <h3 className="mb-2 text-xl font-bold text-gray-900">{item.title}</h3>
                  <p className="mb-2 text-gray-600">{item.description}</p>
                  <div className="inline-flex items-center gap-2 rounded-lg bg-emerald-50 px-3 py-1 text-sm font-semibold text-emerald-700">
                    <CheckCircle2 className="h-4 w-4" />
                    {item.action}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Resources */}
        <section>
          <h2 className="mb-8 text-3xl font-bold text-gray-900">Additional Resources</h2>
          <div className="grid gap-6 md:grid-cols-2">
            <a
              href="https://asic.gov.au/regulatory-resources/find-a-document/regulatory-guides/rg-97-disclosing-fees-and-costs-in-pdss-and-periodic-statements/"
              target="_blank"
              rel="noopener noreferrer"
              className="group flex items-start gap-4 rounded-xl border border-gray-200 bg-white p-6 transition-all hover:border-blue-300 hover:shadow-lg"
            >
              <ExternalLink className="mt-1 h-5 w-5 text-gray-400 transition-colors group-hover:text-blue-600" />
              <div>
                <h3 className="mb-2 font-semibold text-gray-900">ASIC RG 97 Official Guide</h3>
                <p className="text-sm text-gray-600">Official regulatory guide from ASIC</p>
              </div>
            </a>

            <a
              href="https://www.ato.gov.au/super/self-managed-super-funds"
              target="_blank"
              rel="noopener noreferrer"
              className="group flex items-start gap-4 rounded-xl border border-gray-200 bg-white p-6 transition-all hover:border-blue-300 hover:shadow-lg"
            >
              <ExternalLink className="mt-1 h-5 w-5 text-gray-400 transition-colors group-hover:text-blue-600" />
              <div>
                <h3 className="mb-2 font-semibold text-gray-900">ATO SMSF Guidelines</h3>
                <p className="text-sm text-gray-600">Self-managed super fund compliance from ATO</p>
              </div>
            </a>
          </div>
        </section>

        {/* CTA */}
        <section className="rounded-2xl bg-gradient-to-br from-emerald-600 to-emerald-700 p-12 text-center">
          <h2 className="mb-4 text-3xl font-bold text-white">
            Deploy ASIC-Compliant AI Agents Today
          </h2>
          <p className="mb-8 text-lg text-emerald-100">
            Pre-configured templates for Australian financial services
          </p>
          <div className="flex flex-col items-center justify-center gap-4 sm:flex-row">
            <Link
              href="/profile"
              className="flex items-center gap-2 rounded-lg bg-white px-8 py-4 font-semibold text-emerald-900 shadow-2xl transition-all hover:scale-105"
            >
              <span>Start Free Trial</span>
              <ArrowRight className="h-5 w-5" />
            </Link>
            <Link
              href="/ai-governance/documentation"
              className="flex items-center gap-2 rounded-lg border-2 border-white/30 bg-white/10 px-8 py-4 font-semibold text-white backdrop-blur-sm transition-all hover:bg-white/20"
            >
              <span>View Documentation</span>
              <BookOpen className="h-5 w-5" />
            </Link>
          </div>
        </section>
      </div>
    </>
  )
}
